# Generated by Django 5.2.5 on 2025-08-28 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(max_length=15)),
                ('cat_desc', models.TextField()),
                ('cat_foto', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=40)),
                ('cli_contacto', models.CharField(max_length=30)),
                ('cli_titulo_contacto', models.CharField(max_length=30)),
                ('cli_direccion', models.CharField(max_length=60)),
                ('cli_ciudad', models.CharField(max_length=15)),
                ('cli_region', models.CharField(max_length=15)),
                ('cli_codigo_postal', models.CharField(max_length=10)),
                ('cli_pais', models.CharField(max_length=15)),
                ('cli_telefono', models.CharField(max_length=24)),
                ('cli_mail', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_nombre', models.CharField(max_length=20)),
                ('emp_apellido', models.CharField(max_length=10)),
                ('emp_titulo', models.CharField(max_length=30)),
                ('emp_mail', models.CharField(max_length=25)),
                ('emp_fecha_nac', models.DateField()),
                ('emp_fecha_contrato', models.DateField()),
                ('emp_direccion', models.CharField(max_length=60)),
                ('emp_celular', models.CharField(max_length=24)),
                ('emp_foto', models.BinaryField()),
                ('emp_notas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('prv_empresa', models.CharField(max_length=40)),
                ('prv_giro', models.CharField(max_length=20)),
                ('prv_contacto', models.CharField(max_length=30)),
                ('prv_direccion', models.CharField(max_length=60)),
                ('prv_pco_postal', models.CharField(max_length=10)),
                ('prv_telefono', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.BigAutoField(primary_key=True, serialize=False)),
                ('ord_fecha', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTrabajo1.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTrabajo1.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=40)),
                ('pro_descripcion', models.CharField(max_length=30)),
                ('pro_precio', models.DecimalField(decimal_places=4, max_digits=19)),
                ('pro_stock', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTrabajo1.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detord', models.BigAutoField(primary_key=True, serialize=False)),
                ('deo_precio', models.FloatField()),
                ('deo_cantidad', models.IntegerField()),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTrabajo1.orden')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTrabajo1.producto')),
            ],
        ),
    ]
